// Automatically generated by makemoduledefs.py.

extern const struct _mp_obj_module_t mp_module___main__;
#undef MODULE_DEF_MP_QSTR___MAIN__
#define MODULE_DEF_MP_QSTR___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },

extern const struct _mp_obj_module_t mp_module_thread;
#undef MODULE_DEF_MP_QSTR__THREAD
#define MODULE_DEF_MP_QSTR__THREAD { MP_ROM_QSTR(MP_QSTR__thread), MP_ROM_PTR(&mp_module_thread) },

extern const struct _mp_obj_module_t mp_module_uasyncio;
#undef MODULE_DEF_MP_QSTR__UASYNCIO
#define MODULE_DEF_MP_QSTR__UASYNCIO { MP_ROM_QSTR(MP_QSTR__uasyncio), MP_ROM_PTR(&mp_module_uasyncio) },

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_MP_QSTR_BUILTINS
#define MODULE_DEF_MP_QSTR_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t mp_module_cmath;
#undef MODULE_DEF_MP_QSTR_CMATH
#define MODULE_DEF_MP_QSTR_CMATH { MP_ROM_QSTR(MP_QSTR_cmath), MP_ROM_PTR(&mp_module_cmath) },

extern const struct _mp_obj_module_t mp_module_framebuf;
#undef MODULE_DEF_MP_QSTR_FRAMEBUF
#define MODULE_DEF_MP_QSTR_FRAMEBUF { MP_ROM_QSTR(MP_QSTR_framebuf), MP_ROM_PTR(&mp_module_framebuf) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_MP_QSTR_GC
#define MODULE_DEF_MP_QSTR_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t mp_module_math;
#undef MODULE_DEF_MP_QSTR_MATH
#define MODULE_DEF_MP_QSTR_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&mp_module_math) },

extern const struct _mp_obj_module_t mp_module_micropython;
#undef MODULE_DEF_MP_QSTR_MICROPYTHON
#define MODULE_DEF_MP_QSTR_MICROPYTHON { MP_ROM_QSTR(MP_QSTR_micropython), MP_ROM_PTR(&mp_module_micropython) },

extern const struct _mp_obj_module_t mp_module_network;
#undef MODULE_DEF_MP_QSTR_NETWORK
#define MODULE_DEF_MP_QSTR_NETWORK { MP_ROM_QSTR(MP_QSTR_network), MP_ROM_PTR(&mp_module_network) },

extern const struct _mp_obj_module_t mp_module_uarray;
#undef MODULE_DEF_MP_QSTR_UARRAY
#define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },

extern const struct _mp_obj_module_t mp_module_ubinascii;
#undef MODULE_DEF_MP_QSTR_UBINASCII
#define MODULE_DEF_MP_QSTR_UBINASCII { MP_ROM_QSTR(MP_QSTR_ubinascii), MP_ROM_PTR(&mp_module_ubinascii) },

extern const struct _mp_obj_module_t mp_module_collections;
#undef MODULE_DEF_MP_QSTR_UCOLLECTIONS
#define MODULE_DEF_MP_QSTR_UCOLLECTIONS { MP_ROM_QSTR(MP_QSTR_ucollections), MP_ROM_PTR(&mp_module_collections) },

extern const struct _mp_obj_module_t mp_module_uctypes;
#undef MODULE_DEF_MP_QSTR_UCTYPES
#define MODULE_DEF_MP_QSTR_UCTYPES { MP_ROM_QSTR(MP_QSTR_uctypes), MP_ROM_PTR(&mp_module_uctypes) },

extern const struct _mp_obj_module_t mp_module_uerrno;
#undef MODULE_DEF_MP_QSTR_UERRNO
#define MODULE_DEF_MP_QSTR_UERRNO { MP_ROM_QSTR(MP_QSTR_uerrno), MP_ROM_PTR(&mp_module_uerrno) },

extern const struct _mp_obj_module_t mp_module_uhashlib;
#undef MODULE_DEF_MP_QSTR_UHASHLIB
#define MODULE_DEF_MP_QSTR_UHASHLIB { MP_ROM_QSTR(MP_QSTR_uhashlib), MP_ROM_PTR(&mp_module_uhashlib) },

extern const struct _mp_obj_module_t mp_module_uheapq;
#undef MODULE_DEF_MP_QSTR_UHEAPQ
#define MODULE_DEF_MP_QSTR_UHEAPQ { MP_ROM_QSTR(MP_QSTR_uheapq), MP_ROM_PTR(&mp_module_uheapq) },

extern const struct _mp_obj_module_t mp_module_io;
#undef MODULE_DEF_MP_QSTR_UIO
#define MODULE_DEF_MP_QSTR_UIO { MP_ROM_QSTR(MP_QSTR_uio), MP_ROM_PTR(&mp_module_io) },

extern const struct _mp_obj_module_t mp_module_ujson;
#undef MODULE_DEF_MP_QSTR_UJSON
#define MODULE_DEF_MP_QSTR_UJSON { MP_ROM_QSTR(MP_QSTR_ujson), MP_ROM_PTR(&mp_module_ujson) },

extern const struct _mp_obj_module_t mp_module_machine;
#undef MODULE_DEF_MP_QSTR_UMACHINE
#define MODULE_DEF_MP_QSTR_UMACHINE { MP_ROM_QSTR(MP_QSTR_umachine), MP_ROM_PTR(&mp_module_machine) },

extern const struct _mp_obj_module_t mp_module_uos;
#undef MODULE_DEF_MP_QSTR_UOS
#define MODULE_DEF_MP_QSTR_UOS { MP_ROM_QSTR(MP_QSTR_uos), MP_ROM_PTR(&mp_module_uos) },

extern const struct _mp_obj_module_t mp_module_urandom;
#undef MODULE_DEF_MP_QSTR_URANDOM
#define MODULE_DEF_MP_QSTR_URANDOM { MP_ROM_QSTR(MP_QSTR_urandom), MP_ROM_PTR(&mp_module_urandom) },

extern const struct _mp_obj_module_t mp_module_ure;
#undef MODULE_DEF_MP_QSTR_URE
#define MODULE_DEF_MP_QSTR_URE { MP_ROM_QSTR(MP_QSTR_ure), MP_ROM_PTR(&mp_module_ure) },

extern const struct _mp_obj_module_t mp_module_uselect;
#undef MODULE_DEF_MP_QSTR_USELECT
#define MODULE_DEF_MP_QSTR_USELECT { MP_ROM_QSTR(MP_QSTR_uselect), MP_ROM_PTR(&mp_module_uselect) },

extern const struct _mp_obj_module_t mp_module_usocket;
#undef MODULE_DEF_MP_QSTR_USOCKET
#define MODULE_DEF_MP_QSTR_USOCKET { MP_ROM_QSTR(MP_QSTR_usocket), MP_ROM_PTR(&mp_module_usocket) },

extern const struct _mp_obj_module_t mp_module_ustruct;
#undef MODULE_DEF_MP_QSTR_USTRUCT
#define MODULE_DEF_MP_QSTR_USTRUCT { MP_ROM_QSTR(MP_QSTR_ustruct), MP_ROM_PTR(&mp_module_ustruct) },

extern const struct _mp_obj_module_t mp_module_sys;
#undef MODULE_DEF_MP_QSTR_USYS
#define MODULE_DEF_MP_QSTR_USYS { MP_ROM_QSTR(MP_QSTR_usys), MP_ROM_PTR(&mp_module_sys) },

extern const struct _mp_obj_module_t mp_module_utime;
#undef MODULE_DEF_MP_QSTR_UTIME
#define MODULE_DEF_MP_QSTR_UTIME { MP_ROM_QSTR(MP_QSTR_utime), MP_ROM_PTR(&mp_module_utime) },

extern const struct _mp_obj_module_t mp_module_uzlib;
#undef MODULE_DEF_MP_QSTR_UZLIB
#define MODULE_DEF_MP_QSTR_UZLIB { MP_ROM_QSTR(MP_QSTR_uzlib), MP_ROM_PTR(&mp_module_uzlib) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_BUILTINS \
    MODULE_DEF_MP_QSTR_CMATH \
    MODULE_DEF_MP_QSTR_FRAMEBUF \
    MODULE_DEF_MP_QSTR_GC \
    MODULE_DEF_MP_QSTR_MATH \
    MODULE_DEF_MP_QSTR_MICROPYTHON \
    MODULE_DEF_MP_QSTR_NETWORK \
    MODULE_DEF_MP_QSTR_UARRAY \
    MODULE_DEF_MP_QSTR_UBINASCII \
    MODULE_DEF_MP_QSTR_UCOLLECTIONS \
    MODULE_DEF_MP_QSTR_UCTYPES \
    MODULE_DEF_MP_QSTR_UERRNO \
    MODULE_DEF_MP_QSTR_UHASHLIB \
    MODULE_DEF_MP_QSTR_UHEAPQ \
    MODULE_DEF_MP_QSTR_UIO \
    MODULE_DEF_MP_QSTR_UJSON \
    MODULE_DEF_MP_QSTR_UMACHINE \
    MODULE_DEF_MP_QSTR_UOS \
    MODULE_DEF_MP_QSTR_URANDOM \
    MODULE_DEF_MP_QSTR_URE \
    MODULE_DEF_MP_QSTR_USELECT \
    MODULE_DEF_MP_QSTR_USOCKET \
    MODULE_DEF_MP_QSTR_USTRUCT \
    MODULE_DEF_MP_QSTR_USYS \
    MODULE_DEF_MP_QSTR_UTIME \
    MODULE_DEF_MP_QSTR_UZLIB \
    MODULE_DEF_MP_QSTR__THREAD \
    MODULE_DEF_MP_QSTR__UASYNCIO \
    MODULE_DEF_MP_QSTR___MAIN__ \
// MICROPY_REGISTERED_MODULES
