#ifndef _QCLOUD_SHADOW_CONFIG_
#define  _QCLOUD_SHADOW_CONFIG_

/* 接收云端返回的JSON文档的buffer大小 */
#define QCLOUD_SHADOW_JSON_BUF_MAX                  (QCLOUD_MQTT_CLIENT_RX_BUF_LEN + 1)

#define QCLOUD_SHADOW_CLIENT_TOKEN_MAX              (QCLOUD_MQTT_DEVICE_CLIENT_ID_MAX + 10)

/* 一个仅包含clientToken字段的JSON文档的最大长度 */
#define QCLOUD_SHADOW_JSON_WITH_CLIENT_TOKEN_MAX          (QCLOUD_SHADOW_CLIENT_TOKEN_MAX + 20)

#define QCLOUD_SHADOW_REQUEST_PENDING_MAX           (10)

#endif

