#ifndef __FLASH_PARTITION_TABLE_H__
#define __FLASH_PARTITION_TABLE_H__

//#define RETENTION_MEM_BASE			0x20028000
//#define RETENTION_MEM_SIZE			0x2000

#ifndef FLASH_BASE
#define FLASH_BASE									(0x10000000)
#endif

#ifndef FLASH_SIZE
#define FLASH_SIZE									(0x00200000)
#endif

#ifndef PRIMARY_PARTITION_OFFSET
#define PRIMARY_PARTITION_OFFSET					(0x0000F000)
#endif

#define PRIMARY_PATTITION_START						0x0000F000
#define PRIMARY_PATTITION_SIZE						0xE1000
//#define USERAPP_SRAM_BASE							0x1FFF0000
#define BACKUP_PATTITION_START						0x000F0000
#define BACKUP_PATTITION_SIZE						0xE1000
#define USERDATA_PATTITION_START					0x001D1000
#define USERDATA_PATTITION_SIZE						0x23000

//memory offset check
#if ((PRIMARY_PATTITION_START < PRIMARY_PARTITION_OFFSET) || (BACKUP_PATTITION_START < PRIMARY_PATTITION_START) || (USERDATA_PATTITION_START < BACKUP_PATTITION_START) || (PRIMARY_PATTITION_START + PRIMARY_PATTITION_SIZE > BACKUP_PATTITION_START) || (BACKUP_PATTITION_START + BACKUP_PATTITION_SIZE > USERDATA_PATTITION_START) || (USERDATA_PATTITION_START + USERDATA_PATTITION_SIZE > FLASH_SIZE))
	#error "flash partition define error!"
#endif

#endif /* __FLASH_PARTITION_TABLE_H__ */
