// Automatically generated by makemoduledefs.py.

extern const struct _mp_obj_module_t mp_module___main__;
#undef MODULE_DEF_MP_QSTR___MAIN__
#define MODULE_DEF_MP_QSTR___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },

extern const struct _mp_obj_module_t mp_module_thread;
#undef MODULE_DEF_MP_QSTR__THREAD
#define MODULE_DEF_MP_QSTR__THREAD { MP_ROM_QSTR(MP_QSTR__thread), MP_ROM_PTR(&mp_module_thread) },

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_MP_QSTR_BUILTINS
#define MODULE_DEF_MP_QSTR_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_MP_QSTR_GC
#define MODULE_DEF_MP_QSTR_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t mp_module_math;
#undef MODULE_DEF_MP_QSTR_MATH
#define MODULE_DEF_MP_QSTR_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&mp_module_math) },

extern const struct _mp_obj_module_t mp_module_micropython;
#undef MODULE_DEF_MP_QSTR_MICROPYTHON
#define MODULE_DEF_MP_QSTR_MICROPYTHON { MP_ROM_QSTR(MP_QSTR_micropython), MP_ROM_PTR(&mp_module_micropython) },

extern const struct _mp_obj_module_t mp_module_uarray;
#undef MODULE_DEF_MP_QSTR_UARRAY
#define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },

extern const struct _mp_obj_module_t mp_module_collections;
#undef MODULE_DEF_MP_QSTR_UCOLLECTIONS
#define MODULE_DEF_MP_QSTR_UCOLLECTIONS { MP_ROM_QSTR(MP_QSTR_ucollections), MP_ROM_PTR(&mp_module_collections) },

extern const struct _mp_obj_module_t mp_module_machine;
#undef MODULE_DEF_MP_QSTR_UMACHINE
#define MODULE_DEF_MP_QSTR_UMACHINE { MP_ROM_QSTR(MP_QSTR_umachine), MP_ROM_PTR(&mp_module_machine) },

extern const struct _mp_obj_module_t mp_module_ustruct;
#undef MODULE_DEF_MP_QSTR_USTRUCT
#define MODULE_DEF_MP_QSTR_USTRUCT { MP_ROM_QSTR(MP_QSTR_ustruct), MP_ROM_PTR(&mp_module_ustruct) },

extern const struct _mp_obj_module_t mp_module_sys;
#undef MODULE_DEF_MP_QSTR_USYS
#define MODULE_DEF_MP_QSTR_USYS { MP_ROM_QSTR(MP_QSTR_usys), MP_ROM_PTR(&mp_module_sys) },

extern const struct _mp_obj_module_t mp_module_utime;
#undef MODULE_DEF_MP_QSTR_UTIME
#define MODULE_DEF_MP_QSTR_UTIME { MP_ROM_QSTR(MP_QSTR_utime), MP_ROM_PTR(&mp_module_utime) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_BUILTINS \
    MODULE_DEF_MP_QSTR_GC \
    MODULE_DEF_MP_QSTR_MATH \
    MODULE_DEF_MP_QSTR_MICROPYTHON \
    MODULE_DEF_MP_QSTR_UARRAY \
    MODULE_DEF_MP_QSTR_UCOLLECTIONS \
    MODULE_DEF_MP_QSTR_UMACHINE \
    MODULE_DEF_MP_QSTR_USTRUCT \
    MODULE_DEF_MP_QSTR_USYS \
    MODULE_DEF_MP_QSTR_UTIME \
    MODULE_DEF_MP_QSTR__THREAD \
    MODULE_DEF_MP_QSTR___MAIN__ \
// MICROPY_REGISTERED_MODULES
