/**
  ******************************************************************************
  * @file   usart.h
  * @author MCD Application Team
  * @brief  configuration of the USART instances
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under Ultimate Liberty license
  * SLA0044, the "License"; You may not use this file except in compliance with
  * the License. You may obtain a copy of the License at:
  *                             www.st.com/SLA0044
  *
  ******************************************************************************
  */
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __USART_H__
#define __USART_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* USER CODE BEGIN Includes */

/* USER CODE END Includes */


/* Pin mapping */

#define USARTx_TX_Pin GPIO_PIN_6
#define USARTx_TX_GPIO_Port GPIOB

#define USARTx_RX_Pin GPIO_PIN_7
#define USARTx_RX_GPIO_Port GPIOB

/* Not generated BY MX (?), was definied in usart_if.c */
#define USARTx_RX_GPIO_CLK_ENABLE()      __HAL_RCC_GPIOB_CLK_ENABLE()
#define USARTx_TX_GPIO_CLK_ENABLE()      __HAL_RCC_GPIOB_CLK_ENABLE()
#define USARTx_CLK_ENABLE()   			 __HAL_RCC_USART1_CLK_ENABLE()

#define USARTx_TX_AF                     GPIO_AF7_USART1
#define USARTx_RX_AF                     GPIO_AF7_USART1

extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef hlpuart1;

void MX_USART1_UART_Init(void);
void MX_USART2_UART_Init(void);
void MX_LPUART1_UART_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __USART_H__*/

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
