if(NOT CMSIS_DSP_LIB_ARM_CORTEXM7LFSP_MATH_MIMXRT1062_INCLUDED)
    
    set(CMSIS_DSP_LIB_ARM_CORTEXM7LFSP_MATH_MIMXRT1062_INCLUDED true CACHE BOOL "CMSIS_DSP_Lib_arm_cortexM7lfsp_math component is included.")

endif()
